### ISSUE TITLE
ember-alpha support

### ISSUE THREAD

**Issue by jasonmit** [ronco/ember-cli-head#10]
```
Assertion Failed: You cannot use `attributeBindings` on a tag-less component: <account@component:head-layout::ember184>
```

Currently fails on glimmer2 with this, I'll try and dig into the issue but I don't believe ember-cli-head uses attributeBindings anywhere so it may be an upstream bug.

**Comment by jasonmit** [comment]
Closing, I was reopening Ember.Component and adding an attribute binding which effected ember-cli-head's component.

**Comment by jasonmit** [comment]
```
ember.debug.js:15157 Uncaught Error: Assertion Failed: Cannot append multiple root views
EmberError	@	ember.debug.js:15157
assert	@	ember.debug.js:5760
assert	@	ember.debug.js:14926
_renderRoot	@	ember.debug.js:10082
appendOutletView	@	ember.debug.js:10010
appendTo	@	ember.debug.js:13199
didCreateRootView	@	ember.debug.js:2918
_setOutlets	@	ember.debug.js:25825
invoke	@	ember.debug.js:1064
flush	@	ember.debug.js:1128
flush	@	ember.debug.js:936
end	@	ember.debug.js:250
(anonymous function)
```

So after resolving the above issue, another issue popped up that I don't believe has to do with my app code and appears to only happen with ember-cli-head enabled.

**Comment by ronco** [comment]
Dang. The appendTo implementation here was always slightly unorthodox to
get the job done. If that's no longer viable we'll need to find an
alternative. I just went on vacation so won't be able to dig in for over a
week. If you have any insights/solutions I'm happy to give them a look.

**Comment by mitchlloyd** [comment]
Hey, fellow `appendTo` user here. There have been some recent commits in Ember to support multiple top level components (these are in Canary today). I have a feeling that this issue may be resolved now.

**Comment by jasonmit** [comment]
@mitchlloyd could you point me to the PR/commits so I can validate my ember build has the change?

This was tested on ember#alpha today.

**Comment by chancancode** [comment]
@jasonmit did that fix it?

**Comment by jasonmit** [comment]
@chancancode no longer seeing the issue.  Thanks everyone.
