### ISSUE TITLE
is it possible to remove ember-cli-head-start and ember-cli-head-end?

### ISSUE THREAD

**Issue by krachtstefan** [ronco/ember-cli-head#17]
is it possible to remove the `<meta name="ember-cli-head-start">` and `<meta name="ember-cli-head-end">`

**Comment by erichonkanen** [comment]
+1 is this possible?

**Comment by erichonkanen** [comment]
@krachtstefan looks like no, will need to submit PR that sets a conditional in the template which can be set in environment/config to disable the default wrapper tags:

https://github.com/ronco/ember-cli-head/blob/master/addon/templates/components/head-layout.hbs

**Comment by krachtstefan** [comment]
> edit: that may be naive as those tags might be used for fastboot etc

That's what I thought :)

**Comment by alex-kovalchuk** [comment]
+1. 2019 year, friends

**Comment by rwjblue** [comment]
Would be nice if this issue explained the motivation. _Why_ do these meta tags matter? What do you gain from removing?

For the most part these meta tags support server side rendering (which is actually a very common use case for this addon).

**Comment by krachtstefan** [comment]
To be honest, I can not reproduce why I needed this back then. We may close this one, except anyone can come up with a good explaination :)

**Comment by erichonkanen** [comment]
I don't remember exactly why I was trying to remove them as it was during work on a previous project, but could have just been cosmetic to eliminate cruft

**Comment by rwjblue** [comment]
OK, going to go ahead and close this for now. Happy to reopen if I've missed something here...
