### ISSUE TITLE
head inside head

### ISSUE THREAD

**Issue by andressrg** [ronco/ember-cli-head#3]
Hey! Very cool addon!

I'm having an issue where my page ends up with:

```html
<head> <!-- index.html's head -->
  <head> <!-- ember-cli-head's head -->
    <!-- things added on head.hbs -->
  </head>
</head>
```

I created a repo that shows this issue: https://github.com/andressrg/test-ember-head-and-fastboot
When I ran it with `ember fastboot` and go to `view-source:http://localhost:3000/my-head` I get:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HeadT</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <base href="/" />
<!-- EMBER_CLI_FASTBOOT_TITLE --><head><meta name="ember-cli-head-start"><!-- `app/templates/head.hbs` -->
<!-- Add content you wish automatically added to the documents head -->
<!-- here. The 'model' available in this template can be populated by -->
<!-- setting values on the 'head-data' service. -->

<meta property="og:title" content="Demo App">
<meta name="ember-cli-head-end">
</head>

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/head-t.css">

    
  </head>
  <body>
    <body><div id="ember385" class="ember-view"><h2 id="title">Welcome to Ember</h2>

<!---->

</div></body>

    <script src="assets/vendor.js"></script>
    <script src="assets/head-t.js"></script>

    
  </body>
</html>
```

Thanks!

**Comment by ronco** [comment]
Hey Andres,

Yes this is peculiar. I think there may be an issue with fastboot
serialization to the document as I see body is also nested here.

I think the fix may lie in ember-fastboot-server itself. Luckily I think
browsers can handle this until we get it resolved.

Thanks for bringing this up. I'll run it down this week.

-Ron

**Comment by ronco** [comment]
I've filed a [bug](https://github.com/ember-fastboot/ember-fastboot-server/issues/30) with ember-fastboot-server for this issue (which is where the problem lies) and submitted a [PR](https://github.com/ember-fastboot/ember-fastboot-server/pull/31) to fix it.

Hopefully we'll see that merged shortly.  Sorry for the delay.

**Comment by andressrg** [comment]
Oh thanks! :smiley:

**Comment by andressrg** [comment]
This is now fixed with your PR. Than you very much!

**Comment by ronco** [comment]
No problem.  Thanks for closing this out!
