### ISSUE TITLE
Acceptance testing

### ISSUE THREAD

**Issue by robwebdev** [ronco/ember-cli-head#38]
Is there a recommended way to test the contents of the `head`?

**Comment by rwjblue** [comment]
In the current version, you can just invoke the component `{{head-layout}}` in a component integration test.

**Comment by robwebdev** [comment]
Thanks, that works for integration testing. I was thinking from an acceptance test perspective though. I am changing properties on the head-data service during page transitions and want to test that everything is hooked up correctly.

**Comment by rwjblue** [comment]
Ah, thats easier. Just do normal DOM assertions on the contents in `document.head`.

**Comment by robwebdev** [comment]
That works perfectly. For some reason I had assumed the `head` of the qunit test page was not the place to be looking, but it is. Thanks!
