### ISSUE TITLE
rootURL favicon link difficulties (not using fastboot)

### ISSUE THREAD

**Issue by nruth** [ronco/ember-cli-head#39]
I may have missed something important from the docs, but I think rootURL is being ignored in the head template.

I've been trying to move 2 lines from my app/index file to the head template to avoid ember-cli clashes on update. Not a big deal, but nice to have.

```
<link rel="icon" href="{{rootURL}}assets/favicon.png">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

The material icons one worked fine, but the favicon one was going in as / instead of prefixing with the rootURL. I've tried using `<link rel="icon" href="/assets/favicon.png">` instead hoping broccoli would swap the path out, but that also gave me no prefix.

Moving the 2 lines back to app/index.html I get the expected links.

Is rootURL supposed to work in the head.hbs template, or is it not the right way to try to do this?

```
ember-source 2.12.2
ember-cli 2.12.3
ember-cli-head 0.4.0
```

**Comment by rwjblue** [comment]
I believe you would need to import the rootURL from config/environment and include it in your head template.

**Comment by nruth** [comment]
That works, thank you!

I'd like to PR adding this to the readme; would it be best as a 1-line comment, or as a second full example?

**Comment by rwjblue** [comment]
A README update would be great, either way works well...

**Comment by janwerkhoven** [comment]
Alternatively use a template helper which exposes environment flags:

```js
// app/helpers/env.js

import { helper } from '@ember/component/helper';
import ENV from 'foo/config/environment';

export default helper(function env(key) {
  return ENV[key];
});
```

```hbs
{{! app/templates/head.hbs }}

{{#if (env 'isProduction')}}
  <link rel="icon" href="{{env 'rootURL'}}assets/favicon.png">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{{/if}}
```
