### ISSUE TITLE
0.4.0 made all my head data stop working

### ISSUE THREAD

**Issue by rwwagner90** [ronco/ember-cli-head#40]
Not sure what exactly happened 😞 . Need to dig up more details, but it's gone locally and built and deployed, so setting back to 0.3.1 for now. Is 0.4.0 preemptive for a newer fastboot or something perhaps?

**Comment by rwjblue** [comment]
Did you follow the upgrade instructions in the README ([see here](https://github.com/ronco/ember-cli-head#upgrade-to-04x))? Did you add `{{head-layout}}` to your `application.hbs`?

**Comment by rwwagner90** [comment]
@rwjblue I did not 😞 . I looked at the changelog and assumed it would be mentioned there if breaking changes were introduced, but I missed that section of the README. Sorry about that!

**Comment by rwjblue** [comment]
No problem! Sorry I didn’t get the changelog updated correctly.
