### ISSUE TITLE
Does this repo really only work with Fastboot now?

### ISSUE THREAD

**Issue by danconnell** [ronco/ember-cli-head#46]
The note in the readme:

```
Take into account that version >= 0.3 of this addon require Ember 2.10+ and fastboot >=1.0.rc1 Please use 0.2.X if you don’t fulfull both requirements.
```

I don't really understand why Fastboot is a requirement now when there are examples where this repo is useful without Fastboot:
1. Keeping the page title up to date using https://github.com/tim-evans/ember-page-title
2. If you're using a service like prerender.io to serve content to crawlers
3. Google says they can crawl JavaScript websites without server side rendering

Is the intention of this repo to only support Fastboot apps going forward?

**Comment by rwjblue** [comment]
Should work fine without fastboot, what issues did you run into?

**Comment by danconnell** [comment]
We're seeing that ember-page-title simply stops working after upgrading it from 3.2.2 to 4.0.2 (4.0.0 being where ember-cli-head was updated). No errors or anything logged in the console, just no page titles.

We added `{{head-layout}}` to our application.hbs, but still no page titles.

We have a head.hbs file defined with `<title>{{model.title}}</title>` in it and if I add `{{log model.title}}` to that file, I see what the page title is supposed to be logged to the console.

We're also using ember-cli-meta-tags and seeing no issues with it.

Is this more likely to be a ember-page-title issue instead of a ember-cli-head issue? I figured it was a ember-cli-head issue since head.hbs is seeing the title, but it's not rendering, and figured it had something to do with that note about fastboot.

**Comment by oskarrough** [comment]
@danconnell could it be this? https://github.com/ronco/ember-cli-head/issues/16

**Comment by danconnell** [comment]
@oskarrough I doubt it. That bug is really old and we weren't having issues with head.hbs until upgrading. And even now, the tags rendered by ember-cli-meta-tags are working but the title tag is not.

**Comment by danconnell** [comment]
Upon further investigation, this is an issue with ember-page-title. Will log a bug there instead.

**Comment by rwjblue** [comment]
The most likely issue for folks upgrading to 4.x is [documented here](https://github.com/ronco/ember-cli-head#upgrade-to-04x), but is basically that users have to directly invoke the `{{head-layout}}` component in their application template...

**Comment by danconnell** [comment]
Logged against ember-page-title as https://github.com/tim-evans/ember-page-title/issues/118.

My problem was specific to 4.0.2 of that package, where a change was made that is removing the title tag after it's rendered by ember-cli-head.
