### ISSUE TITLE
Meta elements "ember-cli-head-start" and "ember-cli-head-end" missing "content" attribute

### ISSUE THREAD

**Issue by samcic** [ronco/ember-cli-head#47]
The [HTML 5.2 Spec, section 4.2.5 ("The meta element")](https://www.w3.org/TR/html52/document-metadata.html#the-meta-element) states that:

> If either name or http-equiv is specified, then the content attribute must also be specified. Otherwise, it must be omitted.

In `ember-cli-head/addon/templates/components/head-layout.hbs`, the `content` attribute is missing from the "ember-cli-head-start" and "ember-cli-head-end" meta tags.

The w3 validator will show this as an error:

![showing results for http www skedda com nu html checker](https://user-images.githubusercontent.com/9308871/37080263-e454b606-21e5-11e8-8cd8-ac325eb667fd.png)

To fix this, can the `content` attribute simply be added with an empty string?

**Comment by rwjblue** [comment]
Thanks for reporting! Yes, I think an empty content attribute would be perfect.

**Comment by samcic** [comment]
Is it necessary to cover the changes in this PR in the unit/integration tests?
