### ISSUE TITLE
private {{-in-element}} deprecated

### ISSUE THREAD

**Issue by krukid** [ronco/ember-cli-head#82]
updating to `ember-source@3.20.0` produces the following deprecation warning on build:

> DEPRECATION: The use of the private `{{-in-element}}` is deprecated, please refactor to the public `{{in-element}}`. ('ember-cli-head/templates/components/head-layout.hbs' @ L1:C0)  [deprecation id: glimmer.private-in-element]

**Comment by rwjblue** [comment]
Was fixed in https://github.com/ronco/ember-cli-head/pull/71 and released as 1.0.0, please upgrade 😸

**Comment by krukid** [comment]
Sorry, it's an `ember-page-title@5.2.4` dependency issue 🤭
